### ISSUE TITLE
Feature: Localization

### ISSUE THREAD

**Issue by RaitoBezarius** [hacksalot/HackMyResume#110]
Hi ! I love HackMyResume approach.
But I find it very hard to use when you want to translate your resumé, you need to hack the theme and I am having difficulties, my theme (forked from modern) returns undefined each time I try to render?

I could give a help on it, but first, how would you like to see this handled? Config file? Languages files?

Thanks in advance and keep the great work :+1: !

**Comment by hacksalot** [comment]
Thanks @RaitoBezarius! Will reply shortly on the localization aspects -- new versions are dropping today/tonight. As a preliminary to deeper localization support we've been removing direct English-language references from the themes through the use of helpers and doing some internal refactoring to make it a bit easier to support language files and potential integrations with libraries like [i18next](https://github.com/i18next/i18next). I assume you're referring to resume localization and not localization of the HMR CLI itself, but either way.

**Comment by RaitoBezarius** [comment]
Yes you're right I'm talking about resume localization! :)
I tried to localize the themes but I admit this is complex sometimes, I do not know which files should I translate, neither how all of this works.

At least, it would be awesome to document "How to translate your resume?", until we get better localization support.

**Comment by hacksalot** [comment]
Also keep in mind you can override section headings (one of the current pain points with theme localization) by using an external options file with the `-o` switch as described [here](https://github.com/hacksalot/HackMyResume/issues/50#issuecomment-169551694). This is a tactical solution, not an all-encompassing localization solution, but may help ease some of the theme-tweaking you have to do in the interim.

**Comment by RaitoBezarius** [comment]
Yet it is not sufficient because some themes "hardcode" some titles like modern with its "About".

**Comment by hacksalot** [comment]
Are you using the `info` key for the About section override? The key name is always the official key from the JSON object model.

```js
{
  "sectionTitles": {
    "info": "Custom About Title",
    "education": "Custom Education Title",
    "service": "Custom Service Title"
    // etc
  }
}
```

If that's not working, I can open a separate issue (feel free to do the same).

**Comment by hacksalot** [comment]
Any further input @RaitoBezarius? If so, leave a comment and I'll re-open. We're always happy to accept PRs around this. Thanks!

**Comment by jjab2020** [comment]
Any Help about how to appear the language section(french,english) thank you very much ;)
