### ISSUE TITLE
--pdf flag is not explained in readme

### ISSUE THREAD

**Issue by adius** [hacksalot/HackMyResume#111]

**Comment by robertmain** [comment]
I can't help but notice the irony of this...

**Comment by adius** [comment]
No I don't ^^

**Comment by hacksalot** [comment]
Added to v1.6.0 either way.

**Comment by robertmain** [comment]
It just struck me as mildly amusing that you opened an issue to complain about a lack of a description....and then failed to provide a description :laughing:

**Comment by adius** [comment]
Seemed to be enough description for @hacksalot (Thanks!)

**Comment by robertmain** [comment]
Yeah it's fine. It just amused me... Little things I guess :-)

**Comment by hacksalot** [comment]
Fixed in 1.6.0. Thanks guys.
