### ISSUE TITLE
Test .json file suggestions?

### ISSUE THREAD

**Issue by vfulco** [hacksalot/HackMyResume#116]
Blown away by the amount of progress made on this project.  Couple of features in the analysis report I didn't think of.  Kudos. 

Updated to latest and tried the default modern theme.  PDF and html render nicely, .doc still a work in progress, .png is truncated.  Much of the rendering is really dependent on the relative completeness/incompleteness of the json file; a very challenging task for the final output.

I typically use the 'richard hendricks' json file from registry.jsonresume.org as my boilerplate to test out all theme format rendering.  Is there another you would recommend before moving on to trying to wrestle/customize our own in to json schema format?

TIA

**Comment by hacksalot** [comment]
Hi @vfulco thanks for the kind words, and your 2nd paragraph is spot-on. The `.doc` formats tend to lag behind a bit and convergence here is one of the milestones for the v1.0 themes release, after which we can update formats in lockstep. Here are some resume sources:

- [fresh-test-resumes](https://github.com/fluentdesk/fresh-test-resumes) has sample/test resumes in both FRESH and JRS formats, including Hendriks, the JRS version of Jane Fullstacker, etc.
- [fresh-resume-starter](https://github.com/fluentdesk/fresh-resume-starter) is the default starter resume created by `hackmyresume new`.
- The official exemplar resume for FRESH resumes is currently [jane-q-fullstacker](https://github.com/fluentdesk/jane-q-fullstacker), also available in JRS format in the fresh-test-resumes repo.

**Comment by vfulco** [comment]
+1
