### ISSUE TITLE
PSA: Add JSON Resume usage warning

### ISSUE THREAD

**Issue by hacksalot** [hacksalot/HackMyResume#118]
HMR should emit the following warning messages when used with a JRS-format resume or theme:

1. JSON Resume **resume-cli** silently uploads user data to the registry over a remote connection without warning.

2. JSON Resume is backed by a for-profit entity (Hired.com) (ie, not really FOSS).

We'll relax these when/if JRS drops the commercial affiliation and stops harvesting user data on the sly. Can also include (undocumented) instructions for removing user data from their registry.

Refs:

- https://github.com/jsonresume/resume-cli/blob/master/lib/export-resume/index.js#L67-L104
- https://github.com/jsonresume/resume-cli/issues/180

**Comment by hacksalot** [comment]
Added in 1.7.0-b

**Comment by thomasdavis** [comment]
Just updating this issue that JSON Resume is not a corporate entity. We had very minor sponsoring for a matter of months and this is no longer the case. 

Though if anyone reading this would like to help me pay for server bills, reach out =D

**Comment by gruebait** [comment]
AFAIK this was abandoned after the jsonresume-cli 1.0.0 changes were announced, JSON Resume is an officially recommended format although the docs may need updating to reflect that.

**Comment by thomasdavis** [comment]
No worries, we are in the process of setting up a board/committee to ensure the longevity of the project. I might reach out to HMR soon to see if someone might represent during meetings as I am sure there will be lots of useful information to share.

**Comment by hacksalot** [comment]
Sorry @thomasdavis I've been moving the past few days. We are officially pro JRS here (this old complaint notwithstanding) and we're hoping to synchronize some of our internal formats with JSON Resume as it grows. Either myself or @tomheon would be happy to give some feedback, feel free to PM at will.
