### ISSUE TITLE
Error: PDF Styling

### ISSUE THREAD

**Issue by robertmain** [hacksalot/HackMyResume#121]
PDF generation is currently producing PDFs with no styling (see below)

![screenshot from 2016-01-24 16 34 09](https://cloud.githubusercontent.com/assets/537684/12537512/ff80a6c6-c2b8-11e5-9792-da4a7811511c.png)

**Comment by hacksalot** [comment]
What theme are we talking?

**Comment by robertmain** [comment]
Oops! Sorry, I forgot to say. Modern theme.

**Comment by hacksalot** [comment]
Thanks! Sanity checks:

- Try the `--pdf phantom` and `--pdf wkhtmltopdf` switches.
- Try `hackmyresume new <blah>.json` followed by `hackmyresume build <blah>.json`. Same issue?
- Try running `wkhtmltopdf` or `phantomjs` directly from the command line, against the generated `.pdf.html` (if present) or `.html` format. Same issue?
- External stylesheet links can sometimes cause this. Make sure you're not doing `--css link` or similar.

**Comment by robertmain** [comment]
1. ![image](https://cloud.githubusercontent.com/assets/537684/12537610/028cae3a-c2bb-11e5-9384-919ab013c124.png)
1. ![image](https://cloud.githubusercontent.com/assets/537684/12537619/26f683b8-c2bb-11e5-81f6-e3aaaf8ee3e4.png)
1. 
![image](https://cloud.githubusercontent.com/assets/537684/12537628/62ff4bce-c2bb-11e5-86de-05442a84db9b.png)

**Comment by hacksalot** [comment]
Thanks for the screens. Pushing a new version with this and some other fixes shortly. Most of the internal code will be moving over to [HackMyAPI](hacksalot/HackMyAPI), with the official HackMyResume CLI being a client.

**Comment by robertmain** [comment]
No probs :) 

>Most of the internal code will be moving over to HackMyAPI, with the official HackMyResume CLI being a client.

Does that mean that basically when we "build" a resume it will be shipped up to an external API for processing first?!

**Comment by hacksalot** [comment]
> Does that mean that basically when we "build" a resume it will be shipped up to an external API for processing first?!

No, that was one of the things that really bothered me about JSON Resume's **resume-cli** tool -- the silent upload of user data to the registry without warning. HackMyResume is local-only, by design. That's a formal requirement. HackMyAPI is just the core (local) resume processing and theme generation code that formerly lived in HackMyResume (also local), but presented without the baggage of the CLI. Just a code restructuring, but one that we knew would probably open up a few bugs, even if it increased the health overall.

**Comment by robertmain** [comment]
Yeah, sorry ) wrote that comment then looked at your repo when you'd pushed it, realised how dumb that comment was and then deleted it :)

**Comment by hacksalot** [comment]
Actually, yes. Good idea. I was thinking more generically of "API" but nowadays that connotes "remote" more often tha not. We'll tweak the name before integrating it.

**Comment by robertmain** [comment]
:+1:

**Comment by hacksalot** [comment]
Do you still see this in 1.7.1?

**Comment by robertmain** [comment]
![image](https://cloud.githubusercontent.com/assets/537684/12610485/f9b21a26-c4df-11e5-9d14-159e13a3b97b.png)

**Comment by hacksalot** [comment]
We just finished the HackMyCore relocation, caffeinization, reintegration as a submodule. Should be able to address this and apply some tests now that the ground has stopped shifting.

**Comment by hacksalot** [comment]
How does this look in 1.7.3?

**Comment by robertmain** [comment]
Looking good here :+1: :tada:
