### ISSUE TITLE
NPM install fails

### ISSUE THREAD

**Issue by antani** [hacksalot/HackMyResume#124]
NPM install fails on MacOSX El Capitan

~ » node --version
v0.10.40
~ » sudo npm install hackmyresume -g 
npm ERR! network connect ETIMEDOUT
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! System Darwin 15.0.0
npm ERR! command "/Users/8288/.nvm/v0.10.40/bin/node" "/Users/8288/.nvm/v0.10.40/bin/npm" "install" "hackmyresume" "-g"
npm ERR! cwd /Users/8288
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! syscall connect
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/8288/npm-debug.log
npm ERR! not ok code 0

**Comment by hacksalot** [comment]
Hi, are you able to install other packages like `npm install adj-noun`? At first glance this looks like a network or access issue.

**Comment by antani** [comment]
Apologies, I had a different npm registry set.
