### ISSUE TITLE
json format changed in 1.7.2 ?

### ISSUE THREAD

**Issue by morenoh149** [hacksalot/HackMyResume#127]
I recently updated to 1.7.2 from 1.4.2(~). Now all my generated pdf don't list everything they used to.

my json file is here
https://gist.github.com/morenoh149/7832e088c44e18a7765b

this is happening with the compact and modern themes. I haven't tested more.
![screen shot 2016-01-28 at 4 55 36 pm](https://cloud.githubusercontent.com/assets/587438/12660089/fcd99fde-c5df-11e5-9acc-ed09cfdb8ca2.png)

^ thats the whole pdf

**Comment by hacksalot** [comment]
There have been a couple breaking changes between those versions. I'll take a look -- FWIW the formats have stabilized a bit now and future changes should be wrapped in an upgrade notification.

**Comment by zlangbert** [comment]
I'm seeing the same thing. For me, between 1.7.0 and 1.7.1 the entire employment section became a few numbers. So just using 1.7.0 for now.

**Comment by hacksalot** [comment]
Fix is in progress for 1.7.3. Thanks for the reports.

**Comment by seiflotfy** [comment]
You haven't pushed yet

**Comment by hacksalot** [comment]
Found several other bugs. We're working this now.

**Comment by hacksalot** [comment]
Should be fixed in 1.7.3. Let me know if you're able to generate the full PDF.

Also removed the ugly gray border from the PDF version.
