### ISSUE TITLE
Building to solo PNG fails

### ISSUE THREAD

**Issue by hacksalot** [hacksalot/HackMyResume#132]
Generating a resume to PNG format works if you do...

    hackmyresume build resume.json to out/resume.all

...but fails if you target the `PNG` format explicitly:

    hackmyresume build resume.json to out/resume.png

The PNG format is unique in that HMR will provide a PNG output for any theme that provides an `.html` output (which is all themes, currently, except for Awesome, which generates pure LaTeX), which means the PNG rendering path needs to render an HTML format internally, and currently HMR doesn't support this kind of nested or dependent rendering in the solo case -- it just happens to work when `.all` is the output because the HTML format is already built and available for the PNG generator to use.

**Comment by iamthechad** [comment]
It may not always work for `.all`. With HMR 1.7.4 and Node 5.3.0 I get the following:

    *** HackMyResume v1.7.4 ***
    Reading FRESH resume: resume.json
    Applying MODERN theme (8 formats)
    Generating TXT  resume: out/resume.txt
    Generating MD   resume: out/resume.md
    Generating DOC  resume: out/resume.doc
    Generating HTML resume: out/resume.html
    Generating PDF  resume: out/resume.pdf
    Generating JSON resume: out/resume.json
    Generating YML  resume: out/resume.yml
    Generating PNG  resume: out/resume.png

    /Users/chad/.nvm/versions/node/v5.3.0/lib/node_modules/hackmyresume/dist/utils/safe-spawn.js:19
            throw {
            ^
    [object Object]

I get a `resume.png.html`, but no resulting PNG

**Comment by RomanTsegelskyi** [comment]
Is get the same error on `OSX`. It might be connected to imaging libraries, since generating `pdf` doesn't work also

**Comment by hacksalot** [comment]
Are you able to run `phantomjs` from the command line? If not, try installing it directly, verifying it's on your path and accessible from your shell, then rerunning HMR.

If not, there have been some changes on `dev` which may address this. We're also considering reincorporating the Phantom dependency although this gets into other issues.

**Comment by RomanTsegelskyi** [comment]
`phantomjs` was on the `PATH`, but `wkhtmltopdf` wasn't (turns out `npm` installs it as lib, not executable). I tried dev and it gave more descriptive message, though it seems to work with stable too. Thanks

**Comment by hacksalot** [comment]
You're welcome! Officially fixed in [1.8.0](https://github.com/hacksalot/HackMyResume/releases/tag/v1.8.0).
