### ISSUE TITLE
Fails to build PDFs and PNGs

### ISSUE THREAD

**Issue by RyenNelsen** [hacksalot/HackMyResume#139]
I am currently on the `dev` branch, and when compiling a sample resume with the command `hackmyresume build resume.json to out/resume.all -p phantomjs` my output is:
```
*** HackMyResume v1.7.5 ***
Reading FRESH resume: resume.json
Applying MODERN theme (8 formats)
Generating TXT  resume: out\resume.txt
Generating MD   resume: out\resume.md
Generating DOC  resume: out\resume.doc
Generating HTML resume: out\resume.html
Generating PDF  resume: out\resume.pdf (with phantomjs)
Generating JSON resume: out\resume.json
Generating YML  resume: out\resume.yml
Generating PNG  resume: out\resume.png
```

Yet `ls`ing the output folder shows:
```
-rw-r--r-- 1 Ryen Ryen  2126 Feb 12 21:19 md.txt
-rw-r--r-- 1 Ryen Ryen 47637 Feb 12 21:19 modern-doc.xml
-rw-r--r-- 1 Ryen Ryen  3011 Feb 12 21:19 modern-html.css
-rw-r--r-- 1 Ryen Ryen 13963 Feb 12 21:19 modern-html.html
-rw-r--r-- 1 Ryen Ryen  3002 Feb 12 21:19 modern-pdf.css
-rw-r--r-- 1 Ryen Ryen  8888 Feb 12 21:19 modern-pdf.html
-rw-r--r-- 1 Ryen Ryen  9562 Feb 12 21:19 resume.json
-rw-r--r-- 1 Ryen Ryen 13963 Feb 12 21:19 resume.png.html
-rw-r--r-- 1 Ryen Ryen  3964 Feb 12 21:19 resume.yml
-rw-r--r-- 1 Ryen Ryen  2467 Feb 12 21:19 txt.txt
```

You can actually see none of the files are converting over: **md.txt**, **modern-doc.xml**, **modern-pdf.html**, and **resume.png.html**. I can only assume that they are html files during conversion.

**Comment by hacksalot** [comment]
Thanks for the heads up -- some temporary turbulence on the `dev` branch, should be resolved shortly.

**Comment by hacksalot** [comment]
Hi @RyenNelsen this should now be resolved (on `dev`). IF not, let me know and I'll re-open if necessary. Thanks~

**Comment by RyenNelsen** [comment]
It's solved for the most part -- just doesn't clean up now.

**Comment by hacksalot** [comment]
Thanks -- could you log an issue for that (or leave more details here)? HmR writes certain supporting files by default along with the main resume outputs.

**Comment by RyenNelsen** [comment]
Sure, I'll open another issue to keep things clean.
