### ISSUE TITLE
Styling messed up for json resume themes

### ISSUE THREAD

**Issue by surendra2014** [hacksalot/HackMyResume#155]
FRESH: `hackmyresume BUILD test_resume.json TO out/rez.all -t compact`   works fine  with styles
JSON  : `hackmyresume BUILD test_resume.json TO out/rez.all -t themes/jsonresume-theme-kendall`
             works fine but styles messed up.

I noticed that css files are generated for fresh but not for json resume themes.

**Comment by camdenb** [comment]
Yeah I'm having this issue too. Seems like most themes are made for webpages so they're usually kinda broken in PDF form.

**Comment by hacksalot** [comment]
I'll take a look- thanks for the report.

**Comment by adenta** [comment]
Here is what I get when I follow the above.

Everything is super small.

This happens with both FRESH and JSON

[rez.pdf](https://github.com/hacksalot/HackMyResume/files/1691288/rez.pdf)

**Comment by hacksalot** [comment]
Thanks @adenta for the sample PDF. That's more of a postage stamp resume. Was this generated through Phantom, wkhtmltopdf, or WeasyPrint?

**Comment by adenta** [comment]
wkhtmltopdf

Should I try Phantom?

**Comment by hacksalot** [comment]
Well, in any case something is broken with wkhtmltopdf or our handling of it. As a sanity check, if you invoke `wkhtmltopdf` from the command line, against the HTML resume generated by HackMyResume...

`wkhtmltopdf resume.pdf.html output.html`

...would the sizing still be messed up?

**Comment by adenta** [comment]
Yes, the sizing is still messed up. Going to try Phantom and will report back.

**Comment by adenta** [comment]
I can confirm this is isolated to wkhtmltopdf

https://cl.ly/3F0u0N2Z050F

Looks like phantom is working about as expected.

**Comment by hacksalot** [comment]
Thanks. If the sizing is also messed up under CLI `wkhtmltopdf` then it's possibly a characteristic of the HTML HackMyResume is emitting. It could also be a wkhtmltopdf bug. Even if it is an wkhtmltopdf bug, the goal of HMR is to emit HTML that most HTML-to-PDF generators can chew through. If we're not doing that, it's a bug, or at least an enhancement.

**Comment by hacksalot** [comment]
I can generate a reasonable `jsonresume-theme-kendall` in the latest `dev` code with:

```bash
git clone https://github.com/LinuxBozo/jsonresume-theme-kendall
npm i
hackmyresume my/resume.json test/out.all -t jsonresume-theme-kendall
```

Is this drastically different from what you guys are seeing?

![image](https://user-images.githubusercontent.com/8078272/35771995-422c1788-0904-11e8-9f21-a4b974a202f8.png)
