### ISSUE TITLE
apostrophes are rendered as &#39; for HTML and PDF artifacts 

### ISSUE THREAD

**Issue by SavvySkylark** [hacksalot/HackMyResume#157]
When generating a PDF or HTML document from FRESH or JSR resume apostrophes are displayed as \&\#39; in the recognition and awards section.

[resume.pdf](https://github.com/hacksalot/HackMyResume/files/226982/resume.pdf)

**Comment by myonn** [comment]
Same issue in the employment section for company name.

**Comment by ryneeverett** [comment]
I'm only seeing this with the default modern theme.

**Comment by ryneeverett** [comment]
The solution is to avoid html escaping by changing the double-bracket template variables to triple-bracket. See [the handlebar docs](http://handlebarsjs.com/expressions.html):

> If you don't want Handlebars to escape a value, use the "triple-stash", ```{{{```

Making this change to the themes fixed this for me, though it seems like there ought to be some way to toggle html escaping globally in this repository.
