### ISSUE TITLE
Custom helper registration from themes

### ISSUE THREAD

**Issue by rasjani** [hacksalot/HackMyResume#158]
Preface:

In the past, I've been basicly writing my CV in vim and then just converting it to pdf and doc based on what ever the needs have been but now im in progress of converting everything to hackmyresume by using freshca format and template. 

Since i'm dev, I love monotype fonts and fixed width data and my main template is still going to be following this rule either in markdown or just text.

Actual issue:

Since hbs is not really primarily intended for txt/markdown formatting, it lacks string padding and splitting helpers. I have no problem for writing these on my own but hackmyresume itself does not support custom helpers from the provided theme.  

Would it be possible add custom helper registeration ? =)

Alternatively, maybe adding https://github.com/assemble/handlebars-helpers as dependency and importing those helpers would be great.

**Comment by jonathan-chin** [comment]
I'd love this also. None of the prebuilt or user submitted themes really give me 100% of what I want, so I want to build my own.

**Comment by hacksalot** [comment]
Absolutely. Look for this in 1.9.0. Sorry for the delay in responding.

**Comment by hacksalot** [comment]
Starting in v1.9.0 you can load custom theme helpers (for FRESH themes) with the `helpers` property in the `theme.json` file. Accepts a single path/glob or an array of paths/globs:

```json
{
  "helpers": ["helpers/*.js", "some-other-helper.js", "../node_modules/handlebars-helpers/**/*.js"]
}
```
