### ISSUE TITLE
'convert' command doesn't correctly detect input format

### ISSUE THREAD

**Issue by therealpxc** [hacksalot/HackMyResume#162]
It always assumes 'FRESH' is the input format, so it only converts to JRS.

**Comment by et** [comment]
I'm getting the same issue. I believe the cause is the following: https://github.com/hacksalot/HackMyResume/blob/master/src/verbs/convert.coffee#L72-L74
I think this should just be detecting the presence of a `basics` property. I'm not sure what the extra stuff is.

**Comment by hacksalot** [comment]
Thanks guys. Fixed in the next release (1.9.0).
