### ISSUE TITLE
Specifying JRS as format resolves in undefined

### ISSUE THREAD

**Issue by MohamadAtieh** [hacksalot/HackMyResume#165]
`hackmyresume NEW r1.json -f jrs`

Output: 

**\* HackMyResume v1.8.0 ***
Creating new JRS resume: r1.json
Error: Failed to create 'undefined'.

It works with FRESH format. I was wondering what's going on here because the error message isn't clear.

**Comment by camdenb** [comment]
I'm having this issue as well

**Comment by lrecknagel** [comment]
Same here ...

**Comment by peternowee** [comment]
Updating the dependency on fresh-resume-starter from 0.2.2 to 0.3.0 fixed this for me. See hacksalot/HackMyResume#183.

**Comment by hacksalot** [comment]
I could've sworn we were shrink wrapping. I'll add this ASAP.

**Comment by hacksalot** [comment]
Fixed in v1.9.0-beta/ thanks
