### ISSUE TITLE
format option not recognized

### ISSUE THREAD

**Issue by ael-code** [hacksalot/HackMyResume#174]
Even if the help message includes the following line:

``` bash
--format -f   The format (FRESH or JSON Resume) to use.
```

when I try to use it along with the `BUILD` command I get:

```
*** HackMyResume v1.8.0 ***
The -d or --debug switch was specified. DEBUG mode engaged.

  Platform:              linux
  Node.js:               v6.8.1
  HackMyResume:          v1.8.0
  FRESCA:                ~0.6.0


  error: unknown option `--format'
```

In any case I think it would be better to have one specific help message for each subcommand, in this case it would be possible to list different options for each subcommand. You can try git cli to see an implementation of what I'm talking about.

**Comment by hacksalot** [comment]
I almost cloned the entire CLI off of Git, given how good it is with subcommands and the general brevity yet clarity of the style. It's terse but informative. We may push this way in the future. As for per-command help, absolutely.

**Comment by hacksalot** [comment]
ps. the `--format` option is for the `NEW` command. For `BUILD`, the format (FRESH or JRS) is inferred from your resume. This will be clearer with per-command help.

**Comment by hacksalot** [comment]
Closing. Now covered by #205.
