### ISSUE TITLE
Convert Resume between Fresh and JSON Resume Format

### ISSUE THREAD

**Issue by ishu3101** [hacksalot/HackMyResume#180]
You can convert your resume from **Fresh format to JSON Resume format** using the command `hackmyresume convert resume-fresh.json TO resume-jrs.json`, but how do you convert from **JSON Resume format to Fresh format**

**Comment by beku** [comment]
confirming that jrs to fresh does not work.

 hackmyresume always auto detects fresh in the input json, even so that is a jrs format.

**Comment by beku** [comment]
Workaround over yaml:

    hackmyresume BUILD resume.json TO out/resume.all
    yaml2json out/resume.yml > resume-fresh.json
    cat resume-fresh.json | ~/programme/yajl/build/reformatter/json_reformat > resume-fresh2.json
    mv resume-fresh2.json resume-fresh.json

It looks like _hackmyresume convert_ looks at some sheeds and then concludes wrongly that its JRS. Instead it should look for FRESH's meta info.

    "meta": {
        "format": "FRESH@0.6.0",
        "version": "0.1.0"
    }

**Comment by ishu3101** [comment]
What is `~/programme/yajl/build/reformatter/json_reformat`? How does the yaml workaround convert from json resume to fresh resume format?

**Comment by beku** [comment]
@ishu3101 
json_reformat comes from yajl. It is used here to beautify the JSON from yaml2json.

The yaml is FRESH format.

**Comment by ishu3101** [comment]
But what is yajl?

**Comment by beku** [comment]
@ishu3101 hehe, we are on github.com . The Yajl C JSON parser library is just round the corner ;) https://github.com/lloyd/yajl

You might use www.jsonlint.com likewise, just online.

**Comment by DancingQuanta** [comment]
Has this been addressed yet?

**Comment by hacksalot** [comment]
Thanks for the report. This is fixed in 1.9.0 which should be out shortly.
