### ISSUE TITLE
specify a theme in options.json file

### ISSUE THREAD

**Issue by oupala** [hacksalot/HackMyResume#197]
I can generate my resume using a locally installed theme by specifying it on the command line:

```bash
node node_modules/hackmyresume/dist/cli/index.js BUILD resume.json TO resume.html --theme node_modules/jsonresume-theme-elegant
```

where the `jsonresume-theme-elegant` is locally installed in the `node_modules` directory.

But when I try to do the same using a json configuration file, it seems to fail and to fallback to the `MODERN` theme:

```bash
node node_modules/hackmyresume/dist/cli/index.js BUILD resume.json TO resume.html --options options.json
```

And the `options.json` file looks like that:

```bash
{
  // Set the default theme to "compact"
  //"theme": "node_modules/jsonresume-theme-elegant",
  //"theme": "jsonresume-theme-elegant",
  "theme": "elegant",
  // Change the "employment" section title text to "Work"
  "sectionTitles": {
    "employment": "Work"
  }
}
```

I've tried many ways to specify the relative path to the theme (see above), but none of them seems to work.

Is it possible to specify the theme via a json options file?

**Comment by ryneeverett** [comment]
Normal relative path syntax works for me: `"theme": "./jsonresume-theme-elegant"`.

**Comment by oupala** [comment]
Thanks a lot @ryneeverett for your answer. As it is working for you, I tried again and again.

I finally tried to validate my `options.json` file and it appears that it was not valid as it contains comments, and [json cannot contain comments](http://stackoverflow.com/questions/244777/can-comments-be-used-in-json).

I remove comments and now my options are effective.

The [documentation should be updated](/mjactual/HackMyResume#file-based-options) to remove comments...

@ryneeverett can you try to add some comments and see if it still works?

**Comment by ryneeverett** [comment]
See #192 and #168. While there are several ways we could improve the situation, I think @peternowee's suggestion that we raise a warning when the options file doesn't validate is the best so far.

**Comment by hacksalot** [comment]
>  I think @peternowee's suggestion that we raise a warning when the options file doesn't validate is the best so far.

Agreed.

**Comment by hacksalot** [comment]
Something like...

```
λ hackmyresume build foo\bar\resume.json to rez.doc -o ..\test-options.json
Error: The specified options file is invalid:
Invalid or corrupt JSON on line 3 column 3.
Make sure the options file contains valid JSON.
```

**Comment by hacksalot** [comment]
Closing as the requested behavior (options validation) is in place for v1.9.0. Thanks!
