### ISSUE TITLE
strange characters in dates

### ISSUE THREAD

**Issue by oupala** [hacksalot/HackMyResume#198]
My generated resume uses the **jsonresume-theme-elegant** theme.

I have some work experience that contains some dates, and the generated result contains some strange characters in dates. See below:

The json:

```json
"startDate": "2010-04-01",
```

The html:

```html
<p class="text-muted"><small><span class="space-right">@@@@~@@@@~@@@@~@@@@~@@@@~@@@@~@@@@~@@@@~@@@@~@@@@~@@@@~@@@@~@@@@~@@
@@~@@@@~@@@@~@@@@~@@@@~@@@@~@@@@~@@@@~@@@@~Apr~@@@@~@@@@~@@@@~@@@@~@@@@~@@@@~@@@@~@@@@~@@@@~@@@@~@@@@~@@@@~@@@@~@@@@~@@@@~@@@@~@@@@~@@@@~@@@@~@@@@~@@@@~@@@@~@@@@, 2010 - Pres
ent</span></small>
```

Do you know where it does come from?

All my files are in ASCII or UTF-8.

**Comment by wnukwiktor** [comment]
Strangly enough, startDate in Education section works as expected, in my case.

**Comment by hacksalot** [comment]
Thanks for the report, I'll see if I can reproduce even though it's been a while since the issue was submitted.

**Comment by oupala** [comment]
I'm still available for testing.

**Comment by hacksalot** [comment]
Thanks @oupala. Fixed for the next release. Same issue seen in #168.

**Comment by oupala** [comment]
I tested a new resume generation with version 1.9.0-beta and it seems to work well.

No more `@@@@` in dates!
