### ISSUE TITLE
Domain expired?

### ISSUE THREAD

**Issue by chothia** [hacksalot/HackMyResume#201]
Hey there,

I noticed hackmyresume.com and please.hackmyresume.com not working. It looks like the domain has expired?

**Comment by jcsibon** [comment]
+1

**Comment by spencerturkel** [comment]
The site redirects to a bogus site that tries to install a chrome extension.

**Comment by Miserlou** [comment]
Please remove this link to a malicious website!

**Comment by hacksalot** [comment]
Thanks for the reports -- yikes. Let me go fire my domain admin. (*"Hacksalot! You're fired!!"*) We've been doing some reorganization and rebranding. More on this in a bit. In the meantime, the URLs have been adjusted to their secure equivalents on FluentDesk, which placement will make more sense once the other tools are released. More on this shortly.

**Comment by so77id** [comment]
domain not working again :'(
