### ISSUE TITLE
Decaffeinate HackMyResume (CoffeeScript -> ES6)

### ISSUE THREAD

**Issue by hacksalot** [hacksalot/HackMyResume#202]
For the v2.0 release I'd like to **migrate HackMyResume from CoffeeScript to ES6-flavored JavaScript**, or whatever subset we can get away with given compatibility requirements. The usual reasons apply:

- Many of CoffeeScript's signature features now exist in JavaScript.
- (Much) Larger base of maintainers and contributors.
- Simplified deployment and debugging.
- Steadily improving ES6 support in Node.

Currently, HMR officially runs on Node 4.0+. With this change, we'd drop older Node versions that don't provide decent feature parity with ES6. Based on the [Node / ES6 support tables][1], this might mean dropping just the 4.x series, or it might eat into our 5.x coverage as well. Dropping support for two major versions just to get some ES6 sugar may be overkill but it's arguable these versions should fall off anyway, especially given the pace at which Node is putting out new ones.

Put another way: **HackMyResume is going back to plain ol' JavaScript. What JavaScript version/idiom should we target?** Vanilla JS for widest platform support or an ES6 mixture at the cost of some older platforms?

[1]: http://node.green

**Comment by jarz** [comment]
Should this really be an issue with tools like NVM available?

**Comment by hacksalot** [comment]
I couldn't think of any scenarios where dropping 4.x through even 6.x inclusive would cause us much pain and suffering, or leave users in the lurch. Even without NVM, Node versions are just so much more lightweight than, say, OS versions. But on the off-chance I'm wrong, this issue is here for people to chime in on.

**Comment by hacksalot** [comment]
Support for Node 4 and 5 is dropped in HackMyResume 1.9.0. CoffeeScript-to-ES6 replacement will happen in 2.0 but we're already, with the CoffeeScript 2.0 upgrade, shipping ES6 in `dist/`. Additionally, the Node 4.x LTS release is about to fall off in April, so we'll end up covering both LTS versions.
