### ISSUE TITLE
What are you supposed to put as the fields for JSON?

### ISSUE THREAD

**Issue by zwhitchcox** [hacksalot/HackMyResume#32]
I tried just putting random json, but I get this error: 

ERROR: Cannot read property 'history' of undefined

**Comment by hacksalot** [comment]
Are you able to load a [sample resume](https://raw.githubusercontent.com/fluentdesk/jane-q-fullstacker/master/resume/jane-resume.json)? You can also try `hackmyresume new myresume.json` to generate an (empty) resume in either format.

**Comment by zwhitchcox** [comment]
Ah ok. Also, by the way, the "Awesome" resume format doesn't work. Here's the output for my console:

```console
resume $ hackmyresume build resume.json to out/index.html -t awesome && mv resume.html index.html && http-server

*** HackMyResume v1.2.0 ***
Reading SOURCE resume: resume.json
Applying AWESOME theme (3 formats)
ERROR: Cannot read property 'outFormat' of undefined
```
