### ISSUE TITLE
ERROR: Object #<Object> has no method 'parse'

### ISSUE THREAD

**Issue by sbhal** [hacksalot/HackMyResume#33]
Platform: Ubuntu 15.10
Node version v0.10.25,
HackMyResume v1.2.0

I am observing below error when trying to BUILD r1.json file to any format.
*** HackMyResume v1.2.0 ***
Reading SOURCE resume: r1.json
ERROR: Object #<Object> has no method 'parse'

Also, getting error when validating json file.
[~/Downloads]  $ hackmyresume VALIDATE r1.json
*** HackMyResume v1.2.0 ***
ERROR: Cannot find module 'FRESCA'
Why do I need FRESCA module even if I am using jrs format?

**Comment by scottsievert** [comment]
I get the same error message `ERROR: Object #<Object> has no method 'parse'` when parsing `resume.json` copy and pasted from jsonresume.org.

Details:
* HackMyResume v1.2.0
* Platform: Mac OS X 10.10.5

**Comment by hacksalot** [comment]
Thanks for reporting this -- fix is in progress and will add better test coverage as well. @sbhal you shouldn't need FRESCA if you're using JRS, if so it's a bug! Investigating now.

**Comment by hacksalot** [comment]
These two issues are fixed in [1.2.1](https://github.com/hacksalot/HackMyResume/releases/tag/v1.2.1). If you still see `ERROR: Object #` I can roll out an additional patch here in a bit. v1.3 will introduce anonymization so you can submit a problematic resume in an issue without necessarily publishing your details, along with http/https support for better sanity- and spot-checking against example resumes.

**Comment by QuiGonSwag** [comment]
I am on Ubuntu 15.04, and I am on hackmyresume version 1.2.1 and I am still having the same error when I try to build my resume that is valid when I run the test:

*** HackMyResume v1.2.1 ***
Reading SOURCE resume: resume.json
ERROR: Object #<Object> has no method 'parse'

**Comment by scottsievert** [comment]
Ditto.

```shell
$ hackmyresume BUILD resume.json TO resume.pdf
*** HackMyResume v1.2.1 ***
Reading SOURCE resume: resume.json
ERROR: Object #<Object> has no method 'parse'

$ hackmyresume VALIDATE resume.json
*** HackMyResume v1.2.1 ***
Reading SOURCE resume: resume.json
Validating resume.json against JSON RESUME schema: VALID!
```

**Comment by hacksalot** [comment]
Fix for `ERROR: Object #<Object>` in progress. I believe this is the same issue as #31.

**Comment by Quantumplation** [comment]
Is there a workaround for this issue currently?  or an ETA on when it'll be fixed?  This project looks really cool, and I'd love to play around with it.

**Comment by hacksalot** [comment]
@Quantumplation Within the next hour or so if not sooner. The fix would be simple but am having some trouble reproducing on any OS X 10.9+, Ubuntu 14+, Win 7+. Will update shortly.

**Comment by sbhal** [comment]
@hacksalot  Can you make new release with your fix?

**Comment by hacksalot** [comment]
@sbhal Please grab v1.2.2 and give it a try-- thanks.

**Comment by sbhal** [comment]
@hacksalot Thanks. Its working for me now.

**Comment by Quantumplation** [comment]
Can confirm that this is fixed.

**Comment by hacksalot** [comment]
Great! Thanks guys.
