### ISSUE TITLE
Error: .doc cannot be opened on certain versions of OS X

### ISSUE THREAD

**Issue by eddywebs** [hacksalot/HackMyResume#36]
none of the generated .doc formats are opening. Tested in osx says resume.doc cannot be opened.

**Comment by Andre0991** [comment]
Seems that LibreOffice can open it, while Pages can't.

**Comment by hacksalot** [comment]
Hi! Thanks for the report. First question: what version(s) of Office are we talking? Office generation works by building WordProcessingML (ie, text/XML) to assemble the final doc so if it's not opening on your platform, odds are the format has a glitch for OS X or there's an incompatible version of Word in the mix. Will add some more tests around OS X generation of Word docs for a baseline. If you rename the `.doc` to `.xml` do you get the same error?

**Comment by Andre0991** [comment]
I can't speak for eddywebs, but that's what happens here:
- Apple Pages 5.6.1 says "“resume.doc” can’t be opened for some reason."
- LibreOffice 4.2.5.2 opens the file normally, but seems that the images are missing in the default theme (I don't have MS Office, so I don't know whether this is expected).
- If the extension is changed to `xml`, Pages doesn't allow it to be open. It says "“resume.xml” could not be handled because Pages cannot open files in the “XML text” format.".

**Comment by hacksalot** [comment]
Thanks @Andre0991. I'll address Apple Pages first. The LibreOffice issues sounds like an HMR bug. Clearly something is up. Will update shortly.

**Comment by eddywebs** [comment]
Hello, I tried opening .doc using Pages 5.5.3 in OSX which failed.
also tried using google docs and it fails to upload the .doc with invalid
file message.

On Fri, Dec 25, 2015 at 2:26 PM, hacksalot <notifications@github.com> wrote:

> Hi! Thanks for the report. First question: what version(s) of Office are
> we talking? Office generation works by building WordProcessingML (ie,
> text/XML) to assemble the final doc so if it's not opening on your
> platform, odds are the format has a glitch for OS X or there's an
> incompatible version of Word in the mix. Will add some more tests around OS
> X generation of Word docs for a baseline. If you rename the .doc to .xml
> do you get the same error?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hacksalot/HackMyResume/issues/36#issuecomment-167259401>
> .
>



-- 
Best Wishes;
Adi

**Comment by hacksalot** [comment]
[v1.3.0](https://github.com/hacksalot/HackMyResume/releases/tag/v1.3.0) has MS Word encoding fixes which may resolve or impact this issue. I'll test against these environments in a bit.

**Comment by hacksalot** [comment]
The MS Word output formats have changed substantially since this thread was last updated. Please comment if this issue persists. Thanks~
