### ISSUE TITLE
Feature: Support groff

### ISSUE THREAD

**Issue by erg0dic** [hacksalot/HackMyResume#37]
cause that would be dope

**Comment by hacksalot** [comment]
Sorry, read this as "gorff" the first time. Long story. Yeah, that would be pretty dope. Do you mean toolchain (ie programmatic) support or a groff-compatible output format?

**Comment by erg0dic** [comment]
the latter

**Comment by hacksalot** [comment]
Added to https://github.com/hacksalot/HackMyResume/blob/dev/ROADMAP.md. Thanks!
