### ISSUE TITLE
Feature: Support emacs org-mode

### ISSUE THREAD

**Issue by wiredsister** [hacksalot/HackMyResume#38]
Seems like a ton of feature overlap with Latex, pdf, text etc being the same options for org.

**Comment by hacksalot** [comment]
Thanks @wiredsister. One eventual goal for the project is to support painless integration with toolchains like org-mode or pandoc. If it's text based, or document-aware, we want it. What's your opinionated take on what this support should look like?

**Comment by hacksalot** [comment]
Added to https://github.com/hacksalot/HackMyResume/blob/dev/ROADMAP.md
