### ISSUE TITLE
Front Page of Hacker News

### ISSUE THREAD

**Issue by diego04** [hacksalot/HackMyResume#39]
Hi, I thought it would be nice to inform you that this post is on the front page of hacker news:
https://github.com/hacksalot/HackMyResume

**Comment by hacksalot** [comment]
Wow, thanks! Awesome. Long-time lurker over there.

**Comment by diego04** [comment]
Your welcome! Good Luck on the project!

**Comment by hacksalot** [comment]
Thanks @dlego04. Closing this for now, catch you over on HN.
