### ISSUE TITLE
Need mor themes!

### ISSUE THREAD

**Issue by hacksalot** [hacksalot/HackMyResume#4]

**Comment by steve-perkins** [comment]
The website (http://please.hackmyresume.com/) indicates that HackMyResume can use any JSON Resume theme.  If this is really true, then I would settle for some mere documentation on where to find those themes.  

The link points only to a gallery website (https://jsonresume.org/themes/) that previews those themes, with no download option.  The JSON Resume people really want you to use *their* online hosting service... and so even though their app is ostensibly open source, they don't make it easy to actually use the source yourself.  

I spent awhile crawling through all of their repos on GitHub, unsuccessfully looking for the actual source code for their themes, before giving up.  Is it crazy to ask *anybody* to post a link to themes source?

This is a neat concept, but I just don't think it's really ready to use yet.

**Comment by hacksalot** [comment]
@steve-perkins you're experiencing some of the same frustrations that motivated me to build HMR in the first place.

> The JSON Resume people really want you to use their online hosting service... and so even though their app is ostensibly open source, they don't make it easy to actually use the source yourself.

I'm not affiliated with JSON Resume beyond submittting a few issues pertaining to the [exact stuff you're complaining about](https://github.com/jsonresume/resume-cli/issues/180). But look at who they're up against: LinkedIn, Monster, and worse. I share your frustration with the lack of local-only generation in the "official" set of JSON Resume tools, which is why HackMyResume features *only local* generation. But even though the JSON Resume workflow may not support out of the box local generation, every piece of server apparatus, every theme, and the JSON Resume standard itself: all 100% open source. I don't think they're required to eviscerate their own future potential business model in order to better adhere to a particular notion of what FOSS actually means.

That said, you've put your finger on the single biggest gap in both of these tools: resume-cli doesn't support local generation, and HackMyResume doesn't support *transparent* use of JSON Resume themes. I can't do anything about the first, but the second is currently the number one development priority for HMR and the reason why HMR themes are still tagged with the beta designator, and if you'll give it just a few more days, I think you'll find usability in this area is greatly improved. In the meantime, to hunt down official JSON Resume theme sources you can follow the GitHub links from here or from the JSON Resume organization account:

- https://www.npmjs.com/search?q=jsonresume-theme

The HackMyResume themes are here:

- https://github.com/fluentdesk/fluent-themes

Please check by in a few days (before the new year, though) for some improvements to how HMR handles foreign themes, and also keep in mind that JSON Resume is prepping for a v1.0.0 drop in the not too distant future. Thanks for the input and let me know if there's any specific functionality you'd like to see. -HAL

**Comment by hacksalot** [comment]
[Edit for brevity] Fix for this is in progress. In v1.3, you'll be able to generate any valid JSON Resume or FRESH theme. Thanks.

**Comment by pmbenjamin** [comment]
@steve-perkins I believe you're looking for this: https://github.com/jsonresume/theme-manager. 
You can also find a smaller number of themes here: https://github.com/fluentdesk/fluent-themes.
The JSON Resume project uses the former for all their themes.

**Comment by mikeycgto** [comment]
Should the `-t` option also handle NPM modules? Then you could `npm install jsonresume-theme-slick` for instance and run `hackmyresume BUILD resume.json TO out/resume.all -t node_modules/jsonresume-theme-slick`

**Comment by pmbenjamin** [comment]
This is related to issue #56.
It should be resolved in v1.3

**Comment by pmbenjamin** [comment]
FYI - I wrote this [FAQ](https://github.com/hacksalot/HackMyResume/wiki/FAQ#themes). Hope it helps future users.

**Comment by hacksalot** [comment]
Thanks @pmbenjamin! I'd prefer to hold off on direct mentions of resume-cli unless we also document that resume-cli silently uploads user data to the registry not only on publish, but for a regular (ostensibly "local") export. We should probably also mentioned that JSON Resume is sponsored by Hired.com for full disclosure. Otherwise, very helpful stuff!

**Comment by hacksalot** [comment]
Closing this out as HackMyResume can now work locally with most/all JSON Resume themes + FRESH themes in [v1.3.0](https://github.com/hacksalot/HackMyResume/releases/tag/v1.3.0).

@mikeycgto That exact syntax is now supported. Install your theme(s) with `npm i jsonresume-theme-[blah]`, then pass the relative path to the theme folder via the `-t` parameter. @pmbenjamin Thanks for your help here.

**Comment by mikeycgto** [comment]
👍

http://michaeljcoyne.me
