### ISSUE TITLE
Error building Jane Q resume

### ISSUE THREAD

**Issue by Mike-Now** [hacksalot/HackMyResume#42]
$hackmyresume BUILD jane.json TO jane.all
    
    *** HackMyResume v1.2.2 ***
    Reading SOURCE resume: jane.json
    Applying MODERN theme (7 formats)
    Generating DOC resume: jane.doc
    Generating HTML resume: jane.html
    Generating MD resume: jane.md
    Generating PDF resume: jane.pdf
    Generating TXT resume: jane.txt
    Generating JSON resume: jane.json
    Generating YML resume: jane.yml
    events.js:142
          throw er; // Unhandled 'error' event
          ^
    
    Error: write EPIPE
        at Object.exports._errnoException (util.js:856:11)
        at exports._exceptionWithHostPort (util.js:879:20)
        at WriteWrap.afterWrite (net.js:764:14)

    $node -v
    v5.2.0

**Comment by Mike-Now** [comment]
Another thing: pdf converter works yet? The output pdf file has 0 bytes.

**Comment by hacksalot** [comment]
Hi @Mike-Now, quick question, is [wkhtmltopdf](http://wkhtmltopdf.org/) installed for your platform? Thanks.

**Comment by Mike-Now** [comment]
Sorry, I didn't notice the "Note" part in the readme. Works as intended after installing wkhtmltopdf.
