### ISSUE TITLE
How to choose fields to be exported?

### ISSUE THREAD

**Issue by Andre0991** [hacksalot/HackMyResume#45]
I filled the address and languages parts on the `json` file, but they don't show up when exporting to any format.

Is it possible to change that?

I think it would be nice to put this on the readme (if it's possible).

Great tool, btw :)

**Comment by burntcookie90** [comment]
It seems like a lot of fields are just ignored, it's unfortuantely become a deal breaker for me.

Specifically:

`resume.samples`

and 

`resume.skills.list`

**Comment by Andre0991** [comment]
I suspect this depends on the theme and we would have to modify it to include another fields.

**Comment by hacksalot** [comment]
Hi gents, short answer here is that all built-in themes should support *all* JSON fields. If not, it's a bug, and most of this stuff should "just work" in v1.3. For now, this is a bug.

@burntcookie90 Apologies, and as a temporary workaround, you can use `resume.skills.sets`. The `skills` section is one of the more fluid (= messy) areas and one of the main reasons why fluent-themes releases are [still tagged with a `beta` designator](https://github.com/fluentdesk/fluent-themes/releases). Again, this is a bug, and will be fixed shortly. Thanks for the report.

@Andre0991 You're correct that it's up to theme, so for example, a business card-style theme doesn't have to present skill histories or employment timelines. For built-in themes, the requirement is that all documented JSON fields (and certainly major stuff like samples and skills) should flow to the resume. Marking this as a bug.

**Comment by burntcookie90** [comment]
@hacksalot awesome, thanks for the update, I'll check back in with the project once it's out of beta then, looking forward to it!

**Comment by Andre0991** [comment]
Cool @hacksalot, thanks.

**Comment by hacksalot** [comment]
Coverage has improved in 1.6.0/1.7.0. It's also now possible to explicitly ignore fields with the `.ignore` property (in both FRESH and JRS resumes). Closing this general issue but feel free to log specific bugs/features as you find them.

**Comment by Andre0991** [comment]
Ok, thanks @hacksalot.
