### ISSUE TITLE
Please annotate your tags

### ISSUE THREAD

**Issue by jleclanche** [hacksalot/HackMyResume#48]
If you annotate your tags (with -a or, better yet, -s), they will show up in `git describe` which is used by various package managers.

**Comment by hacksalot** [comment]
Ah yes. +1. Will add to the release workflow. Thanks for mentioning this.

**Comment by hacksalot** [comment]
v1.3.0 and future versions should carry annotated tags. If there's time I'll annotate the previous release tags also.

**Comment by jleclanche** [comment]
Thanks!
