### ISSUE TITLE
Example of Theme?

### ISSUE THREAD

**Issue by thetomester13** [hacksalot/HackMyResume#49]
It'd be great if you could give an example of how to create a theme (or even just show the source of the current themes) so that other people can build off of those. Thanks!

**Comment by hacksalot** [comment]
Thanks @thetomester13, will add a dedicated HOWTO for this in the next version. In the meantime, theme sources are here:

- https://github.com/fluentdesk/fluent-themes
- https://jsonresume.org/themes/ --> (multiple GH repos)

**Comment by thetomester13** [comment]
Sweet, thanks!!

**Comment by hacksalot** [comment]
@thetomester13 HackMyResume can also work locally with [JSON Resume themes](https://www.npmjs.com/search?q=jsonresume-theme) in the latest version. Thanks.

**Comment by thetomester13** [comment]
:+1:
