### ISSUE TITLE
Change language used in headings

### ISSUE THREAD

**Issue by Andre0991** [hacksalot/HackMyResume#50]
Is it possible to modify the words used in each heading, such as "About", "Skills", etc? I would like to translate them to my native language.

Not sure whether this is a `HackMyResume` or `jsonresume` issue.

Thanks :)

**Comment by hacksalot** [comment]
Hi! Ability to rename sections is already implemented locally and we should be pushing this to production in the next 24-48 hours or so. In the meantime, you can always open up the theme files directly (look in node_modules/fluent-themes in wherever your HMR is installed) and change the wording there -- it's just plain text. [For example](https://github.com/fluentdesk/fluent-themes/blob/master/themes/modern/src/modern-html.html#L70-L73):

```html
<section id="employment">
  <header>
  <h3>Employment</h3>
  </header>
```

Beyond that, we'll be adding better i18n support, ability to rename/reorder sections, and locale-aware date and other formats. So this is very much a priority.

(Also, just to clarify, HackMyResume isn't officially affiliated with JSON Resume, but we do support the JRS format.)

**Comment by Andre0991** [comment]
Cool.

Thanks for your answer.

**Comment by miloskroulik** [comment]
Is this ability described somewhere? I wasn't able to find it so far...

**Comment by hacksalot** [comment]
@Andre0991 you're welcome! @miloskroulik Should be in tonight's push. Will update here.

**Comment by hacksalot** [comment]
@miloskroulik @Andre0991 To change resume headings:

1. Create a JSON options file mapping section names to your preferred display name:

    ```json
    "sectionTitles": {
      "employment": "empleo",
      "education": "schooling",
      "skills": "skillz"
    }
    ```

2. Run `hackmyresume build resume.json -o <path-to-options-file>`.

**Comment by Andre0991** [comment]
@hacksalot Perfect, thank you.
