### ISSUE TITLE
wkhtmltopdf error handling

### ISSUE THREAD

**Issue by robertmain** [hacksalot/HackMyResume#51]
Currently if you do not have wkhtmltopdf installed, a node.js `ENOENT` is raised in the console. I think that this should be caught intelligently and a warning (by HackMyResume) should be raised warning the user that no PDF will be generated without this library, but everything else is fine and they shouldn't worry. Otherwise, it looks like the resume build has failed or the lib doesn't work...

**Comment by hacksalot** [comment]
100% correct and nothing should require the user to install a platform-specific PDF generation library in the first place, unless the user is actually interested in generating PDFs. Which many users aren't. Will address this in the next release or feel free to submit a PR. Thanks!

**Comment by zhuangya** [comment]
i did some search on how to generate pdf easier.. but don't have a solution yet.

on OS X, you can almost print everything to pdf by clicking some buttons on the GUI, however seems taht it don't have a way to "print to pdf" programmatically yet :(

**Comment by robertmain** [comment]
That sounds like the osx I remember :-)

**Comment by hacksalot** [comment]
Merging with #58. Thanks!
