### ISSUE TITLE
How to export in smoke signal format?

### ISSUE THREAD

**Issue by nmai** [hacksalot/HackMyResume#52]
I was told I could export my CV as smoke signals but I can't seem to figure out how. Can anybody help? Is this a bug?

**Comment by hacksalot** [comment]
Hi @nmai, yes. You'll need a campfire, a blanket, and lots of green wood. This should probably be added to the README. If you're near a park, you could also try our carrier pigeon format as a temporary workaround. Thanks for the report and I'll update when this has been addressed.

**Comment by nmai** [comment]
Thanks I really appreciate the help. The carrier pigeon workaround is a good suggestion, if a bit hacky. I'm fairly sure I'm up-to-date on my bird flu vaccinations so I'll give it a shot!

**Comment by hacksalot** [comment]
Closing this temporarily but will add this information to the README. Thanks!

**Comment by nmai** [comment]
No worries! Thanks for taking the time to look into this issue. This is what keeps me motivated to keep contributing to open source.
