### ISSUE TITLE
Feature: Support for Scribus SLA format

### ISSUE THREAD

**Issue by luzpaz** [hacksalot/HackMyResume#54]
Would it be possible to autogenerate a Scribus .sla using HackMyResume?

**Comment by hacksalot** [comment]
Yes, assuming an .sla text/XML format under the hood, HMR could generate it. This would require a template but not much in the way of code. If this interests you, and you have a sample handy, we can tear off an experimental theme.

**Comment by hacksalot** [comment]
Added to https://github.com/hacksalot/HackMyResume/blob/dev/ROADMAP.md. Thanks!
