### ISSUE TITLE
Themese up-to-date?

### ISSUE THREAD

**Issue by vfulco** [hacksalot/HackMyResume#55]
Given the version # > 1.0, are the themes stated on the description page assumed to be fully functional?  I am getting: 

1) strange alignment issues when I render contact info (name, phone, email, other links) for the themes positive and minimist in html.  I have verified the json file against general and jsonresume schema.

2) Also apostrophe "s" is rendering as pure HTML I think. I.E. "Chairman&#39;s Council Award" 

TIA

P.S. Haa, github is recogizing the html tag for question #2. after I save it.  Suffice to say, when I build html , I get ampersand-number sign-pound-39.

**Comment by vfulco** [comment]
P.S.S. I realize it looks even worse if there is no "label" field completed in the JSON resume file which is rendered almost opaque for this theme when there is a value.

**Comment by hacksalot** [comment]
Hi @vfulco thanks for the report. Quick question, are you on the latest v1.2 version of HMR? We're about to move the themes project out of beta which should fix most of these encoding/display issues and make it easier to choose between FRESH/JRS and custom themes.

**Comment by vfulco** [comment]
I am.

 fluentcv --version
*** FluentCV v1.2.0 ***
ERROR: Cannot read property 'warn' of undefined

npm --version
2.11.3

**Comment by hacksalot** [comment]
@vfulco if you are still experiencing these glitches in v1.4.x please open another issue -- we've had a lot of code changes. Thanks for the report.
