### ISSUE TITLE
some links are malformed.

### ISSUE THREAD

**Issue by morenoh149** [hacksalot/HackMyResume#57]
using my json file https://gist.github.com/morenoh149/36d2edf0844df7f319aa

and the following command `hackmyresume BUILD resume.json TO out/resume.all -t positive`

I get the following pdf http://harrymoreno.com/assets/harryMorenoResume.pdf

some hyperlinks are broken and show `<a
href="https://itunes.apple.com/us/app/temp/id1022731803">https://itunes.apple.com/us/app/temp/id1022731803</a>` for example.

**Comment by hacksalot** [comment]
Hi @morenoh149 thanks for mentioning this -- recent HTML and Markdown formatting/encoding updates should resolve this issue. Will update here when these are released.

**Comment by zvory** [comment]
I am also encountering  this issue, although I suppose it will be fixed soon.

**Comment by hacksalot** [comment]
This has been resolved. Fix should be in shortly. Thanks-

**Comment by hacksalot** [comment]
Secondary issue, justification settings in the Word version of the above-linked resume don't work for shorter entries. Will log an issue.

**Comment by morenoh149** [comment]
please chime in when a new npm version gets released and related issue gets resolved.

**Comment by hacksalot** [comment]
This should be fixed in 1.4.0, available on NPM. If not, I'll re-open. Thanks.

**Comment by morenoh149** [comment]
ah okay. So the fix made was to modern. But I'm also seeing issues regarding anchor tags in bullet points under and employment entry using the `compact` theme.http://harrymoreno.com/assets/harryMorenoResume.pdf

should I open a separate issue?

**Comment by hacksalot** [comment]
Please do and I'll roll it into the next theme update -- I see the issues you're referring to, should be a quick fix. Thanks.
