### ISSUE TITLE
Ampersand ( & ) symbols cause Word documents to break

### ISSUE THREAD

**Issue by pmbenjamin** [hacksalot/HackMyResume#66]
## Description
I had an ampersand in a few places in my `resume.json` and discovered that the generated Word Document errs upon opening due to a corruption.

## Steps
1. My `resume.json` can be found here: https://gist.github.com/pmbenjamin/b4ba2959bbd036f494a2#file-resume-v2-json (CTRL+F or CMD+F to search for `&` symbol).
2. `hackmyresume build resume.json` generates all documents successfully.
3. Opening the `doc` file throws error: 
```
Illegal name character.
Location: Line: 15, Column: 1593
```
## Resolution
1. Open `doc` file in a text editor
2. Go to location specified in error message (e.g. line 15, column: 1593)
3. Remove `&` and save.

I doubt that this is a fault of `HackMyResume` per se, but thought I should create an issue for it in case others encounter this.

**Comment by hacksalot** [comment]
Thanks for the info @pmbenjamin. Looks to me like the `&` isn't being encoded properly for the Word format, which is XML internally. Will roll this into v1.3.

**Comment by hacksalot** [comment]
A lot of these Word encoding errors have been fixed in [v1.3.0](https://github.com/hacksalot/HackMyResume/releases/tag/v1.3.0). Probably worth trying again. Thanks.

**Comment by hacksalot** [comment]
Please re-open if you experience this issue again as the code has changed significantly. Thanks!

**Comment by jkoo7yeha** [comment]
On 29 Dec 2015 20:09, "Peter Benjamin" <notifications@github.com> wrote:
>
> Description
>
> I had an ampersand in a few places in my resumejson and discovered that
the generated Word Document errs upon opening due to a corruption
>
> Steps
>
> 1 My resumejson can be found here:
https://gistgithubcom/pmbenjamin/b4ba2959bbd036f494a2#file-resume-v2-json
(CTRL+F or CMD+F to search for & symbol)
> 2 hackmyresume build resumejson generates all documents successfully
> 3 Opening the doc file throws error:
>
> Illegal name character
> Location: Line: 15, Column: 1593
>
> Resolution
>
> 1 Open doc file in a text editor
> 2 Go to location specified in error message (eg line 15, column: 1593)
> 3 Remove & and save
>
> I doubt that this is a fault of HackMyResume per se, but thought I should
create an issue for it in case others encounter this

**Comment by hacksalot** [comment]
Hi @pmbenjamin, using HackMyResume v1.3.0 I am able to generate and open your v2 resume in MS Word 2013, although I notice that the colored skill bars are missing (make sure each skillset includes a "level" with a value of "master, advanced, beginner, intermediate" or 1 through 10):

![image](https://cloud.githubusercontent.com/assets/8078272/12069195/52179e74-aff1-11e5-81a4-befae7b95fcc.png)


@jkoo7yeha are you experiencing this issue? Thanks.
