### ISSUE TITLE
Add option to remove terminal colors

### ISSUE THREAD

**Issue by hacksalot** [hacksalot/HackMyResume#72]
Some users won't like the colors, some terminals won't display them properly. Add an option to turn off or customize output colorization.

**Comment by zhuangya** [comment]
i think change terminal output color module to [chalk](https://npmjs.org/package/chalk) would be better

cause there's [an option for enabling/disabling colors](https://github.com/chalk/chalk#chalkenabled).

**Comment by hacksalot** [comment]
I concur. Chalk support added in the latest **dev** branch. Thanks!

**Comment by hacksalot** [comment]
Colors can now be disabled with the `--no-color` flag or force-enabled with the `--color` flag. We've also switched to Chalk which should do some auto-detection of terminal color capabilities, which can be overridden with the above swtiches.

**Comment by zhuangya** [comment]
:+1:
