### ISSUE TITLE
Downplay the reference to FluentCV Desktop

### ISSUE THREAD

**Issue by StevenBlack** [hacksalot/HackMyResume#76]
The mention of FluentCV Desktop is prominent, maybe overbearing, on the [HackMyResume home page](http://please.hackmyresume.com/).

When we follow that link, it's very evident that FluentCV Desktop isn't released yet.

So it's a bit of a bum steer.   It takes up about 60% of the home page by area, which is probably excessive and inadvisable at this juncture.

**Comment by hacksalot** [comment]
Hi @StevenBlack -- apologies for that. FluentCV Desktop uses HackMyResume (well, FluentCV:CLI) internally, so all the bugs found here would be bugs there too, and it seemed impolite to release it with known, fixable bugs. We'll update the landing/download page to make this clear and get some legit release info in play. Thanks for pointing this out. ps. I do expect an FCVD release here in the next 24-72 hours.

**Comment by StevenBlack** [comment]
ah... cool!

Hey great work over the past few days.  I've been watching.  I'm teaching my teenager about coding and I'm *so* glad to see progress on themes over the holiday period here.  HackMyResume's going to be an introduction to programming with the practical application of... hopefully getting a job!   The mysterious ways of Dad.

**Comment by 861** [comment]
Where can I download the fluentcv desktop ？Can you give me the link ？ even is not  alpha  version

**Comment by a1fx** [comment]
Same trying to find it
