### ISSUE TITLE
Rethink FluentDate + end dates

### ISSUE THREAD

**Issue by jarz** [hacksalot/HackMyResume#84]
HMR automagically subs today for present/now/current @ [fluent-date.js:32](https://github.com/hacksalot/HackMyResume/blob/d0c181ee8c70aebe1d86af4492cb25eb4750770f/src/core/fluent-date.js#L32). That means my current job always ends this month.

**Comment by hacksalot** [comment]
Agreed. Reworking this per fluentdesk/fresh-themes/issues/23.

**Comment by robertmain** [comment]
So is this issue intended to address HMR putting in the current date for the end date whenever you compile? To my mind, omitting an end date should be interpreted to mean "Still continuing" so a job with no end date should read "01-01-2001" - "Present"

**Comment by hacksalot** [comment]
Fixed in 1.6.0.
