### ISSUE TITLE
Error: Corrupted PDF being generated

### ISSUE THREAD

**Issue by robertmain** [hacksalot/HackMyResume#87]
**OS:** Debian Linux v8
**HackMyResume Version:** 1.3.1
**NPM Version:** 3.3.6
**Node Version:** 5.0
## 

I generated a new resume(as a test for something else) and was able to successfully build it into various formats including PNG(this is a seriously cool feature, great work!!)..however, although the PNG seemed to work I got an error(see below) at that point and the PDF cannot be opened...

```
$ hackmyresume NEW test.json
*** HackMyResume v1.3.1 ***
Creating new FRESH resume: test.json

$ hackmyresume BUILD test.json
*** HackMyResume v1.3.1 ***
Applying MODERN theme (5 formats)
Reading resume: test.json
Generating DOC resume: out/resume.doc
Generating HTML resume: out/resume.html
Generating MD resume: out/resume.md
Generating PDF resume: out/resume.pdf
Generating TXT resume: out/resume.txt
Generating JSON resume: out/resume.json
Generating YML resume: out/resume.yml
Generating PNG resume: out/resume.png
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Gtk-Message: Failed to load module "canberra-gtk-module"
    at Socket.<anonymous> (/home/robert/.nvm/versions/node/v5.0.0/lib/node_modules/hackmyresume/node_modules/wkhtmltopdf/index.js:79:17)
    at Socket.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)
```

The PDF appeared to be broken or corrupted somehow because I dragged it into chrome and just got nothing (not even a blank page). It was like there was nothing there.

**Comment by aksakalli** [comment]
+1

**OS:** Ubuntu 14.04
**HackMyResume Version:** 1.3.1
**NPM Version:** 3.3.12
**Node Version:** 5.1.0

**Comment by seysn** [comment]
Same here

<b>OS:</b> Arch Linux
<b>HackMyResume Version:</b> 1.3.1
<b>NPM Version:</b> 3.5.2
<b>Node Version:</b> 5.3.0

**Comment by hacksalot** [comment]
v1.4 will be out today and has side-by-side PDF generation through either wkhtmltopdf or Phantom. May help shed some light on these issues or provide a workaround.

**Comment by Faiz7412** [comment]
I tried already converting the generated html to pdf using wkhtmltopdf. It breaks. Definitely not worth it. The layout is totally screwed up in pdf. I tried almost all of the themes available on npm. Everyone of them breaks

**Comment by hacksalot** [comment]
Hi @Faiz7412, are you referring to FRESH themes or JSON Resume themes? You should be able to generate FRESH themes to PDF unless you're having some other error. JSON Resume themes aren't controlled by or affiliated with HMR or FluentCV, so the process of supporting them is a bit slower, but ultimately we should support both. You can also try the JRS's homegrown tools like resume-cli.

If you grab the latest HackMyResume (1.4) default generation has switched to Phantom, and you can choose the engine with the `--pdf` switch, eg, `hackmyresume build resume.json --pdf wkhtmltopdf`. This may not solve your issue, but it should shed some light. Thanks.

**Comment by Faiz7412** [comment]
Hi @hacksalot , I was referring to JSON Resume themes. I installed HackMyResume recently, and event though I already have PhantomJS, it installed it again saying the installed version is wrong. Which version does of phantomjs does this project use? I have installed v1.9.0 from source. Will try FRESH themes now. Also, I used wkhtmltopdf command to convert my resume hosted at registry.jsonresume.org to pdf.
Thanks! I can't wait for the next version of HMR:)

**Comment by Faiz7412** [comment]
@hacksalot I get the following error while using fresh themes

```
faiz@FZ:~/github/resume$ hackmyresume BUILD resume.json TO out/resume.pdf -t awesome

*** HackMyResume v1.4.0 ***
Reading resume: resume.json
Applying AWESOME theme (1 format)
ERROR: Cannot read property 'outFormat' of undefined
TypeError: Cannot read property 'outFormat' of undefined
    at single (/home/faiz/.nvm/versions/node/v4.2.3/lib/node_modules/hackmyresume/src/verbs/generate.js:151:31)
    at /home/faiz/.nvm/versions/node/v4.2.3/lib/node_modules/hackmyresume/src/verbs/generate.js:104:17
    at Array.forEach (native)
    at build (/home/faiz/.nvm/versions/node/v4.2.3/lib/node_modules/hackmyresume/src/verbs/generate.js:103:13)
    at Command.execVerb (/home/faiz/.nvm/versions/node/v4.2.3/lib/node_modules/hackmyresume/src/index.js:174:28)
    at Command.<anonymous> (/home/faiz/.nvm/versions/node/v4.2.3/lib/node_modules/hackmyresume/src/index.js:109:16)
    at Command.listener (/home/faiz/.nvm/versions/node/v4.2.3/lib/node_modules/hackmyresume/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:87:13)
    at Command.emit (events.js:172:7)
    at Command.parseArgs (/home/faiz/.nvm/versions/node/v4.2.3/lib/node_modules/hackmyresume/node_modules/commander/index.js:615:12)
```

**Comment by robertmain** [comment]
Yeah, I'm seeing this too

**Comment by hacksalot** [comment]
@Faiz7412 Thanks for the info. The `awesome` theme only supports LaTeX right now. It basically just injects your resume data into the [Awesome-CV](https://github.com/posquit0/Awesome-CV) LaTeX structure.

Do you get the same error with a different theme (`modern`, `compact`, `positive`, etc.)? Adding another round of test cases shortly for better coverage here.

@robertmain That's what the `contributors` field is there for!

**Comment by Faiz7412** [comment]
I tried other themes, still getting errors

```
faiz@FZ:~/github/resume$ hackmyresume BUILD resume.json TO out/resume.pdf -t positive

*** HackMyResume v1.4.0 ***
Reading resume: resume.json
Applying POSITIVE theme (5 formats)
Generating PDF  resume: out/resume.pdf
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: /bin/sh: 1: wkhtmltopdf: not found
    at Socket.<anonymous> (/home/faiz/.nvm/versions/node/v4.2.3/lib/node_modules/hackmyresume/node_modules/wkhtmltopdf/index.js:79:17)
    at Socket.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)
faiz@FZ:~/github/resume$ hackmyresume BUILD resume.json TO out/resume.pdf -t modern

*** HackMyResume v1.4.0 ***
Reading resume: resume.json
Applying MODERN theme (5 formats)
Generating PDF  resume: out/resume.pdf
The MODERN theme says: "To get colored skill 
progress bars, make sure your resume includes a `level` 
element for each skill!"
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at Object.exports._errnoException (util.js:874:11)
    at exports._exceptionWithHostPort (util.js:897:20)
    at WriteWrap.afterWrite (net.js:763:14)
faiz@FZ:~/github/resume$ hackmyresume BUILD resume.json TO out/resume.pdf -t compact

*** HackMyResume v1.4.0 ***
Reading resume: resume.json
Applying COMPACT theme (5 formats)
Generating PDF  resume: out/resume.pdf
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at Object.exports._errnoException (util.js:874:11)
    at exports._exceptionWithHostPort (util.js:897:20)
    at WriteWrap.afterWrite (net.js:763:14)
faiz@FZ:~/github/resume$ hackmyresume BUILD resume.json TO out/resume.pdf -t minimist

*** HackMyResume v1.4.0 ***
Reading resume: resume.json
Applying MINIMIST theme (5 formats)
Generating PDF  resume: out/resume.pdf
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at Object.exports._errnoException (util.js:874:11)
    at exports._exceptionWithHostPort (util.js:897:20)
    at WriteWrap.afterWrite (net.js:763:14)
faiz@FZ:~/github/resume$ 
```

**Comment by hacksalot** [comment]
@Faiz7412 Working on reproducing this, will update.

**Comment by robertmain** [comment]
@hacksalot yeah i know, but I haven't done much coding - I've just sat in the issue tracker and winged about stuff so I guess it's nice to get recognition :)

**Comment by Faiz7412** [comment]
After trying HMR on Ubuntu, I gave it a try on ElementaryOS. It's giving the following error:

```
faiz@FZ:~/github/resume/out$ hackmyresume BUILD resume.json TO out/resume.pdf -t compact

*** HackMyResume v1.3.1 ***
Applying COMPACT theme (5 formats)
Reading resume: resume.json
Generating PDF resume: out/resume.pdf
[TypeError: Cannot read property 'markdownify' of undefined]
Generating PDF resume: out/resume.pdf
[TypeError: Cannot read property 'markdownify' of undefined]
faiz@FZ:~/github/resume/out$ hackmyresume BUILD resume.json TO out/resume.pdf -t modern

*** HackMyResume v1.3.1 ***
Applying MODERN theme (5 formats)
Reading resume: resume.json
Generating PDF resume: out/resume.pdf
[TypeError: Cannot read property 'markdownify' of undefined]
Generating PDF resume: out/resume.pdf
[TypeError: Cannot read property 'markdownify' of undefined]
```

**Comment by robertmain** [comment]
$ hackmyresume BUILD resume.json TO out/resume.all

    *** HackMyResume v1.4.2 ***
    Reading resume: resume.json
    Applying MODERN theme (5 formats)
    Generating TXT  resume: out\resume.txt
    Generating MD   resume: out\resume.md
    Generating DOC  resume: out\resume.doc
    Generating HTML resume: out\resume.html
    Generating PDF  resume: out\resume.pdf
    ERROR: PDF generation failed. Make sure wkhtmltopdf is installed and accessible
    from your path.
    Generating JSON resume: out\resume.json
    Generating YML  resume: out\resume.yml
    Generating PNG  resume: out\resume.png
    The MODERN theme says: "To get colored skill
    progress bars, make sure your resume includes a `level`
    element for each skill!"
    ERROR: spawn wkhtmltopdf ENOENT
    events.js:141
          throw er; // Unhandled 'error' event
          ^

    Error: spawn wkhtmltopdf ENOENT
        at exports._errnoException (util.js:860:11)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
        at onErrorNT (internal/child_process.js:344:16)
        at doNTCallback2 (node.js:450:9)
        at process._tickCallback (node.js:364:17)
        at Function.Module.runMain (module.js:459:11)
        at startup (node.js:136:18)
        at node.js:972:3


Aside from anything else, it's worth noting that I do have a skill level filled in for each skill.

**Comment by hacksalot** [comment]
Thanks for the information on this issue, all. There have been some changes in [1.5.0](https://github.com/hacksalot/HackMyResume/releases/tag/v1.5.0) to how HackMyResume handles PDF generation.

Specifically, **HMR now performs PDF generation over each engine's command-line interface**.

Instead of talking to Phantom or wkhtmltopdf over a programmatic API, which exposes us to a lot of potential errors in a cross-platform context, HMR speaks to these tools the way a human would: over the command line.

```bash
phantomjs rasterize.js <input>.html <output>.pdf
wkhtmltopdf <input>.html <output>.pdf
```

It happens behind the scenes in a spawned process, but essentially there's no difference. This turns out to be cleaner than going through the API for a couple reasons.

- It allows people to install HackMyResume without triggering a massive inline download of Phantom/wkhtmltopdf with node-gyp involvement, etc. Instead, those dependencies have been removed, and now and in the future, HackMyResume will try to be more intelligent about whatever tools the user has installed, or chooses to install, on his system.

- The CLI version of these engines (Phantom.js, wkhtmltopdf) tends to be more stable than the API, either because the CLI has more actual users, or because using the API requires an npm package dependency with subsequent massive Phantom download and node-gyp involvement.

- We can support arbitrary PDF engines this way, with close to zero additional code. (In v1.5.1, we'll add support for arbitrary PDF engines. The idea is that you should be able to use any PDF engine that exposes a CLI. Open an issue or submit a PR if there's a specific (CLI-based) toolchain you'd like included.)

- We can draw a line in the sand between rendering errors that happen *in the third-party PDF engine* versus errors that are caused by a bug in HMR. If you're able to use the command-line `wkhtmltopdf` or `phantomjs` binary to build a PDF (or other artifact), then you should also be able to use HackMyResume to generate that same PDF. If not, it's a bug. On the other hand, if your command-line version of `wkhtmltopdf` or `phantomjs` is broken, that's an error that should be submitted to those projects.

- The previous release erroneously stated that the default generation engine was Phantom. It's actually still `wkhtmltopdf`. You can choose the specific engine via `--pdf wkhtmltopdf` or `--pdf phantom` as usual.

Thanks! Feel free to open new issues for new flavors of PDF generation glitches as you find them.

**Comment by robertmain** [comment]
Well I just generated a working, openable PDF of my resume. I'm calling this one fixed(for me at least). I guess I have a minor niggle which is that the page break is in a strange place (right in the middle of the employment section) but I don't know if that is a theme related issue or not.....either way. Issue fixed! :party: :balloon:

**Comment by hacksalot** [comment]
@robertmain Re: your earlier comment. It always struck me as a little unbalanced that a dev can submit a one-line change and GitHub will auto-detect them as a "contributor", but the dev who submits a dozen legit issues to the same repo doesn't bump the contributor count. Almost as if sloc were more important than actual contribution and engagement.

**Comment by Faiz7412** [comment]
Doesn't the styling of the generated pdf break for you? @robertmain ?

**Comment by hacksalot** [comment]
In progress.. once dev is stable again you can do `npm i hacksalot/hackmyresume#dev -g` to try it with latest.

@Faiz7412 What sort of breakage are you seeing? Missing styles, as if the stylesheet didn't get pulled in correctly, or some other kind of breakage?

**Comment by Faiz7412** [comment]
@hacksalot  Missing styles. The design breaks and is completely different from the original, which looks ugly. Should I upload images to illustrate?

**Comment by robertmain** [comment]
@Faiz7412 last time i checked, the PDF was being generated just fine and dandy

**Comment by robertmain** [comment]
@Faiz7412 were you referring to what I'm seeing in #121 with v1.1.6?

**Comment by hacksalot** [comment]
Is anybody still experiencing this specific issue? Let us know.

**Comment by hacksalot** [comment]
Just a note for people experiencing PDF generation issues in general, as of 1.9.0 HackMyResume supports three PDF engines (separate installation req'd)...

- [wkhtmltopdf](https://wkhtmltopdf.org)
- [PhantomJS](http://phantomjs.org)
- [WeasyPrint](http://weasyprint.org)

...and can be made to support any PDF engine that has either a) a command-line interface or b) a Node-accessible API.
