### ISSUE TITLE
LaTex generation

### ISSUE THREAD

**Issue by dsdeiz** [hacksalot/HackMyResume#89]
I can't seem to find documentation regarding latex generation. I found #44 and gave it a try:

```
$ hackmyresume build  jane-resume.json to jane-resume.all -t awesome

*** HackMyResume v1.3.1 ***
Applying AWESOME theme (1 formats)
Reading resume: jane-resume.json
Generating LATEX resume: jane-resume.latex
Generating JSON resume: jane-resume.json
Generating YML resume: jane-resume.yml
```

Although I don't see the `jane-resume.latex` file. I do see the YAML file though.

Commands that I tried but didn't work:

* `hackmyresume build  jane-resume.json to jane-resume.tex`
* `hackmyresume build  jane-resume.json to jane-resume.latex`
* `hackmyresume build  jane-resume.json to jane-resume.latex -t awesome`

**Comment by hacksalot** [comment]
@dsdeiz That particular theme recreates the "as is" Awesome-CV structure. Look for a `src\latex\examples` subfolder and run your `xelatex` there. If you have any issues, let me know.

**Comment by dsdeiz** [comment]
Oh okay. So I guess it depends on the theme whether it supports LaTex generation? In this case, `awesome` is the only theme (or only theme in core) that supports it?

**Comment by hacksalot** [comment]
Yes, currently. The idea with LaTeX generation in HackMyResume is:

- Treat LaTeX as a destination format (not a source format).
- Help users generate LaTeX bundles (eg, templatized version of permissively licensed LaTeX projects).

We should have better LaTeX support in future versions including basic Markdown-to-LaTeX.

**Comment by hacksalot** [comment]
Feel free to log an issue or submit a PR if you'd like HMR to support a specific LaTeX package. Thanks!
