### ISSUE TITLE
Merging two resumes is failing

### ISSUE THREAD

**Issue by esell** [hacksalot/HackMyResume#91]
It's possible this is user error but I wanted to post here and see. I have taken the base "Richard Hendriks" JSON from jsonresume.org and created an additional resume with the following content:

    {
      "skills": [
        {
          "name": "Cat Herder",
          "level": "Master",
          "keywords": [
            "tabby",
            "feline",
            "tuna"
          ]
        }
      ]
    }

When I run `hackmyresume BUILD base.json test.json TO out.pdf` it errors out with:

    Reading resume: base.json
    Reading resume: test.json
    ERROR: Cannot read property 'name' of undefined
    TypeError: Cannot read property 'name' of undefined
        at Object.module.exports.toFRESH     (/usr/local/lib/node_modules/hackmyresume/src/core/convert.js:29:25)
        at Object.module.exports.loadOne (/usr/local/lib/node_modules/hackmyresume/src/core/resume-    factory.js:69:64)
        at /usr/local/lib/node_modules/hackmyresume/src/core/resume-factory.js:38:21
        at Array.map (native)
        at Object.module.exports.load (/usr/local/lib/node_modules/hackmyresume/src/core/resume-    factory.js:37:22)
        at build (/usr/local/lib/node_modules/hackmyresume/src/verbs/generate.js:72:32)
        at Command.execVerb (/usr/local/lib/node_modules/hackmyresume/src/index.js:168:28)
        at Command.<anonymous> (/usr/local/lib/node_modules/hackmyresume/src/index.js:105:16)
        at Command.listener     (/usr/local/lib/node_modules/hackmyresume/node_modules/commander/index.js:301:8)
        at Command.emit (events.js:110:17)

Doing just a `hackmyresume BUILD base.json TO out.pdf` works ok, it's only when I add in the `test.json` file to be merged that it fails. 

`hackmyresume VALIDATE base.json test.json TO out.pdf` comes back with:

    Reading resume: base.json
    Reading resume: test.json
    Reading resume: TO
    Reading resume: out.pdf
    Validating base.json against JSON RESUME schema: VALID!
    Validating test.json against JSON RESUME schema: VALID!
    Validating TO against AUTO schema: BROKEN
    ERROR: Error: ENOENT, no such file or directory 'TO'
    Validating out.pdf against AUTO schema: BROKEN
    --> OUT.PDF contains invalid JSON on line 1 column 1. Unable to validate.
        INTERNAL: SyntaxError: Unexpected token %

I am on version 1.4.0 of hackmyresume.

**Comment by RichyHBM** [comment]
There are a minimum number of fields that need to be present in both the json files, your test.json file does not have the name nor info fields which IIRC are required.

Make sure both files validate correctly, also, is that meant to be jsonresume or fresca?
Validating a fresca json with just this content gives me:
```
{
  "meta": {
    "format": "FRESH@0.1.0",
    "version": "0.1.0"
  }
}
```

```
> hackmyresume VALIDATE cv2.json
Reading resume: cv2.json
Validating cv2.json against FRESH schema: INVALID
--> RESUME.NAME is required
--> RESUME.INFO is required
```

Which indicates that at a bare minimum both files need the following:
```
{
  "name": "Jane Q. Fullstacker",
  "meta": {
    "format": "FRESH@0.1.0",
    "version": "0.1.0"
  },
  "info": {
  }
}
```

**Comment by esell** [comment]
Thanks @RichyHBM, that was it. I had to add the "basics" section into my test.json file and then it worked.

I had been using the test resume from https://github.com/hacksalot/HackMyResume/blob/master/test/resumes/jrs-0.0.0/richard-hendriks.json which I believe is the jsonresume format.

I'll go ahead and close this out, thanks again for the help!
