### ISSUE TITLE
Feature: Needs support for a Clubs/Orgs field

### ISSUE THREAD

**Issue by vidia** [hacksalot/HackMyResume#92]
As a student I am involved in a handful of clubs that are directly relevant to my career, and I would not call these "volunteer" roles. 

As a Software Engineer, projects are incredibly important to have on resumes.

**Comment by hacksalot** [comment]
Couldn't agree more. This should be in place tomorrow.

https://github.com/fluentdesk/FRESCA/blob/dev/schema/fresh-resume-schema.json#L286-L367

**Comment by robertmain** [comment]
+1 on this

**Comment by hacksalot** [comment]
Changing title from

> Needs support for a Projects and Clubs/Orgs field

to

> Needs support for a Clubs/Orgs field

...now that HMR and FRESH support `projects`.

**Comment by hacksalot** [comment]
Fixed in the latest HMR 1.6.0 and fresh-themes-0.14.0-beta. Thanks for the report.
