### ISSUE TITLE
Compact theme anchor bug

### ISSUE THREAD

**Issue by morenoh149** [hacksalot/HackMyResume#94]
the resume [here](http://harrymoreno.com/assets/HMresumeCompact.pdf)
![screen shot 2016-01-07 at 3 54 55 pm](https://cloud.githubusercontent.com/assets/587438/12182583/077c45de-b557-11e5-9bd5-87a026f168f1.png)

the json file is https://gist.github.com/morenoh149/36d2edf0844df7f319aa

the theme is incorrectly making the entire bullet point an anchor. Is this a misuse of the theme?

**Comment by hacksalot** [comment]
Sorry for the delay, completely missed this issue. Should be fixed in 1.6.0. Leave a comment if the issue persists and I'll re-open. Thanks~
